### ISSUE TITLE
Loosing TOC

### ISSUE THREAD

**Issue by ghost** [webstacknl/qpdf#3]
Hi!

First, thanks for your bundle that saves us with the problem of margins on the cover when using WKHTMLTOPDF. 

Our strategy was to generate cover first with options reseted and then to merge our content using your bundle.

We've just discover that using this method, we were loosing TOC (in the left pane + links on TOC page).

I'm not sure it's a problem from your bundle but I was wondering if you've faced this kind of trick before and if you have some advice for us to fix this?

Thanks in advance for your answer.
Fanch

**Comment by mwansinck** [comment]
Hi @fanchyfanch 

Missing the TOC isn't caused by this bundle. This bundle is only a wrapper around the QPDF binary. Also I don't have a trick that solves this, but a little search on Google give me the following info; https://stackoverflow.com/questions/50832536/build-a-toc-when-concatenating-pdfs
